from services.ai_service import get_ai_service
from services import db_services
from services.prompts import template_prompts

def generate_ai_template(prompt: str, name: str, ratio: str, company_id: int) -> dict:
    """Generates a new blank template using AI."""
    ai = get_ai_service()
    company_data = db_services.get_company_data(company_id) or {}
    
    sys_prompt = template_prompts.template_creation_from_prompt_system_prompt()
    user_prompt = template_prompts.template_creation_from_prompt_user_prompt(company_data, prompt)
    
    result = ai.generate_image(sys_prompt, user_prompt, aspect_ratio=ratio)
    
    if result.get("success"):
        return {
            "success": True, 
            "data": {
                "bytes": result["content"],
                "name": name,
                "ratio": ratio,
                "prompt": prompt
            }
        }
    return {"success": False, "error": result.get("error")}

def modify_ai_template(original_prompt: str, mod_prompt: str, ratio: str, company_id: int) -> dict:
    """Modifies a template by regenerating it with an appended prompt."""
    ai = get_ai_service()
    company_data = db_services.get_company_data(company_id) or {}
    
    combined_prompt = f"{original_prompt}\n\nModification Request: {mod_prompt}"
    
    sys_prompt = template_prompts.template_creation_from_prompt_system_prompt()
    user_prompt = template_prompts.template_creation_from_prompt_user_prompt(company_data, combined_prompt)
    
    result = ai.generate_image(sys_prompt, user_prompt, aspect_ratio=ratio)
    
    if result.get("success"):
        return {"success": True, "data": result["content"]}
    return {"success": False, "error": result.get("error")}

def save_generated_template(company_id: int, name: str, ratio: str, constraints: str, image_bytes: bytes) -> dict:
    """Uploads the generated bytes to storage and saves the template record in DB."""
    tpl_url = db_services.upload_image(image_bytes, folder="templates")
    if not tpl_url:
        return {"success": False, "error": "Failed to upload template image to storage."}
        
    data = {
        "company_id": company_id,
        "template_info": name,
        "aspect_ratio": ratio,
        "template_constraints": constraints,
        "template_url": tpl_url
    }
    if db_services.create_template(data):
        return {"success": True, "data": data}
    return {"success": False, "error": "Failed to save template to database."}

def save_manual_template(company_id: int, name: str, ratio: str, constraints: str, image_bytes: bytes = None) -> dict:
    """Saves a manually created template to DB, uploading an image if provided."""
    tpl_url = None
    if image_bytes:
        tpl_url = db_services.upload_image(image_bytes, folder="templates")
        if not tpl_url:
            return {"success": False, "error": "Failed to upload template image to storage."}
            
    data = {
        "company_id": company_id,
        "template_info": name,
        "aspect_ratio": ratio,
        "template_constraints": constraints,
        "template_url": tpl_url
    }
    if db_services.create_template(data):
        return {"success": True, "data": data}
    return {"success": False, "error": "Failed to save manual template to database."}

def update_template_details(template_id: int, update_data: dict) -> dict:
    """Wrapper to update a template."""
    res = db_services.update_template(template_id, update_data)
    if res is not None:
        return {"success": True, "data": res}
    return {"success": False, "error": "Failed to update template."}
